---
kind: Template
apiVersion: v1
metadata:
  name: pg-connection-test
  annotations:
    description: PostgreSQL connection test.
    tags: pg-connection-test
  labels:
    app: pg-connection-test

objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      app: "pg-connection-test"
    name: "pg-test"
  spec:
    name: latest
    lookupPolicy:
      local: true

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "pg-connection-test"
    labels:
      app: "pg-connection-test"
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
    source:
      git:
        uri: "https://github.com/harshad16/thoth-pg-connection-test"
        ref: "master"
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-thoth-ubi8-py36:latest
        env:
          - name: ENABLE_PIPENV
            value: "1"
          - name: UPGRADE_PIP_TO_LATEST
            value: ""
          - name: "THOTH_DRY_RUN"
            value: "0"
          - name: "THOTH_ADVISE"
            value: "0"
          - name: "THAMOS_VERBOSE"
            value: "1"
          - name: "THAMOS_DEBUG"
            value: "0"
          - name: "THAMOS_CONFIG_TEMPLATE"
            value: ".thoth.yaml"
          - name: "THAMOS_CONFIG_EXPAND_ENV"
            value: "1"
    output:
      to:
        kind: ImageStreamTag
        name: "pg-test:latest"
    resources:
      limits:
        memory: "512Mi"
        cpu: 500m
      requests:
        memory: "512Mi"
        cpu: 500m
